<?php

/**
 * JobeetJob
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Yuya Takeyama
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class JobeetJob extends BaseJobeetJob
{
    public function __call($method, $args)
    {
        // slugify してフィールドの値を取得.
        if (preg_match('/^get(.+?)Slug$/', $method, $matches)) {
            $next = "get{$matches[1]}";
            return Jobeet::slugify($this->$next());
        }
        return parent::__call($method, $args);
    }
}
