dev:
  doctrine:
    class: sfDoctrineDatabase

test:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=blog_test'

all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=blog'
      username: root
      password: goldenbug
